### ISSUE TITLE
1. persistent, non-persistent state, 2. how to get the history and 3. roadmap

### ISSUE THREAD

**Issue by matu3ba** [jake-stewart/jfind.nvim#11]
1. I do see
```
local JFIND_OUT_PATH = CACHE .. "/jfind_out"
local JFIND_EXCLUDES_PATH = CACHE .. "/jfind_excludes"
```
but `inotifywait -e modify,create,delete -m ~/.cache/jfind_out` shows no writes for either, but maybe I'm doing things wrong?
Would you be interested in vimscript/lua implementation of async output reading or would that make the design too complex?
If this is an intentional tradeoff, then this should be documented in the README or a DESIGN document.

2. I do assume the history is not yet implemented? Would be very nice to have a searchable search history. :) I do see `history_limit: INT            Default number of items to store in the history file` in `jfind`, but no indication of how its read within `jfind.nvim`.

3. A roadmap would be nice.

**Comment by jake-stewart** [comment]
i haven't touched the neovim async stuff, so i'm not sure how complex it is. i'll take a look at it a day and get back to you.

as for history, i'm thinking about reimplementing it. the way it works currently is that recently selected items appear at the bottom of the list so that you can easy choose a recent item using arrow keys and enter. i think it makes more sense that history is just a list of search terms and you press `ctrl-n` and `ctrl-p` to navigate previous searches. i'll probably do that today.

there is no roadmap. jfind is a very solid 1.0. it has all the features + polish to be a good tool. i think it needs much better documentation and a possible next feature is previews.

**Comment by jake-stewart** [comment]
for the first point, does jfind.nvim not work at all for you then? do you have `$HOME` set?

**Comment by matu3ba** [comment]
> for the first point, does jfind.nvim not work at all for you then? do you have $HOME set?

It works, but I'd like to do (eventually) abit more advanced stuff like sharing results (absolute paths + line mostly) between neovim instances. For now, I use zoxide into the dir, search and `:Fabs` to yank into copy register after opening, but its not that nice.

**Comment by jake-stewart** [comment]
normally with jfind and fzf, you will run them in the shell like so `find . -type f | jfind`. once completed, the chosen item is printed into stdout so that you can pipe it into another program/variable.

for example: `cat $(find . -type f | jfind)`.

i remember that i had problems piping only stdout from the neovim terminal buffer. my quick fix is to redirect the result into a file `jfind_out` and then read that from within neovim once jfind is over. i delete this file if it exists before running jfind to ensure that we do not read the previous jfind results.

hopefully it makes more sense how `jfind_out` works now. here's how i would copy the result of jfind from within neovim:

```lua
  require("jfind").findFile({
      formatPaths = false,
      hidden = true,
      callback = {
          [Key.DEFAULT] = function(path)
              vim.fn.setreg("+", path)  -- copy path to system clipboard
              vim.cmd.edit(path)  -- edit path
          end,
      }
  })
```

**Comment by faridsaid20** [comment]
> i haven't touched the neovim async stuff, so i'm not sure how complex it is. i'll take a look at it a day and get back to you.
> 
> as for history, i'm thinking about reimplementing it. the way it works currently is that recently selected items appear at the bottom of the list so that you can easy choose a recent item using arrow keys and enter. i think it makes more sense that history is just a list of search terms and you press `ctrl-n` and `ctrl-p` to navigate previous searches. i'll probably do that today.
> 
> there is no roadmap. jfind is a very solid 1.0. it has all the features + polish to be a good tool. i think it needs much better documentation and a possible next feature is previews.

Preview is much awaited feature :) Especially for live grep.
Good job with the plugin so far. Life saver in a big project!

**Comment by jake-stewart** [comment]
@matu3ba history now works out of the box with `ctrl-n` and `ctrl-p`. you will need to recompile jfind and use the jfind.nvim 2.0 branch

this 2.0 branch also has file previews @faridsaid20
