### ISSUE TITLE
more cli shortcuts / better cursor movements

### ISSUE THREAD

**Issue by matu3ba** [jake-stewart/jfind.nvim#12]
Most relevant shortcuts:
- goto start of line
- goto end of line
- delete last word
- delete until start of line
- delete until end of line
- navigate 1 or multiple up
- navigate 1 or multiple down
- yank result path (path:line:column)
- yank result line

Can you think of any more, which are relevant?

**Comment by jake-stewart** [comment]
currently there is `ctrl-u` for clear line, `ctrl-a` for duplicate query, `ctrl+j`, `ctrl+k` and arrow keys for navigating the selector up and down.

i could add `ctrl-w` for deleting back a word since it's a pretty standard binding.

i will not add the yanking into jfind. instead, you could add a keybind within the jfind.nvim plugin. for example:
```lua
require("jfind").findFile({
    formatPaths = true,
    hidden = true,
    callback = {
        [Key.DEFAULT] = vim.cmd.edit,
        [Key.CTRL_Y] = function(path)
            -- yank the name/path using this function
            print(path, require("jfind").formatPath(path))
        end,
    }
})
```

i do not want that much power in terms of keybindings. you are not supposed to spend much time in jfind. you search for an item (backspacing etc if you make a mistake) and then perform an action on that item.

EDIT: i will also add `ctrl-e` and `ctrl-a` for start of line/end of line since they are also standard keybindings. i'll remap the duplicate query to something else.

**Comment by jake-stewart** [comment]
i added `ctrl-e`, `ctrl-a`, `ctrl-w`, `ctrl-f`, `ctrl-b` for editing navigation, `ctrl-p` and `ctrl-n` for history. recompile jfind and use 2.0 branch to use.

**Comment by matu3ba** [comment]
Thanks for the nice work. It feels now very usable besides result selection, but maybe thats just my muscle memory.

`ctrl-a` does not work as expected: Instead of going to beginning of line, it uses the following mapping:
```
map('t', '<C-q>', [[<C-\><C-n>]], opts) -- Quit terminal editing
map('t', '<C-a>', [[<C-\><C-n><C-w>]], opts) -- quit And enter windowing
```

Is this intended?

`C-f` has also quite some timeout before being applied, because I use the same mapping to start jfind.
