### ISSUE TITLE
New preview seems not to work

### ISSUE THREAD

**Issue by faridsaid20** [jake-stewart/jfind.nvim#14]
Took latest from main in https://github.com/jake-stewart/jfind

rebuild it, Here is git log.
![image](https://github.com/jake-stewart/jfind.nvim/assets/119894088/49c666f5-7b3f-4b6c-92e6-79fa67250fd2)

Changed branch to 2.0 for jfind.nvim plugin. Even uninstalled and reinstalled to be sure.

![image](https://github.com/jake-stewart/jfind.nvim/assets/119894088/4ac1d981-3002-4587-bd66-d3395a44413a)

Then copy pasted the liveGrep from readme, which has preview enabled.
![image](https://github.com/jake-stewart/jfind.nvim/assets/119894088/e2668c41-eeb8-43b9-b973-cf0759cc719d)

But there is no preview..
![image](https://github.com/jake-stewart/jfind.nvim/assets/119894088/a318e2af-69f9-4e45-9dfd-a78769879906)

**Comment by jake-stewart** [comment]
looks like i was checking whether the `bat` executable exists incorrectly.

```lua
        preview = ternary(
            vim.fn.executable("bat"),
            "bat --color always --theme ansi --style plain",
            "cat"
        )
```

this code snippet was wrong, since `vim.fn.executable("bat")` returned `0` which is considered `true` for lua... anyway it is fixed now. if you want colors in your preview, i recommend installing bat and jfind.nvim should use it out of the box.
