### ISSUE TITLE
Feature request for circular list of matches

### ISSUE THREAD

**Issue by faridsaid20** [jake-stewart/jfind.nvim#15]
A nice to have feature :)
Is there a way to jump from end to start and vise versa in the list of matches?

1     <- we are here
2
3
4
5

If I press up arrow then result should be

1     
2
3
4
5   <- we are now here

If I press down arrow then result should be

1 <- we are now here
2
3
4
5

But right now we are just stack at the edges of the matches

**Comment by jake-stewart** [comment]
i pushed to jfind the ability to add `"wrap_item_list": true` to `config.json`.

the way jfind is optimised makes it slower at accessing worse matches. imagine you have 1,000,000 results. jfind will only sort the first 256 results until you scroll high enough to sort more. by wrapping around, you force jfind to sort all 1,000,000 results which is very slow.

this has sparked some thought though. i am wondering if i could in the future partial sort only what the user sees. until then, `wrap_item_list` will remain false by default.

also, wrapping will not be allowed on `--command` (live grep) since new results are loaded only when you scroll to them.

**Comment by faridsaid20** [comment]
There is no wrap_item_list in the config.
Did you push it to branch 2.0?

![image](https://github.com/jake-stewart/jfind.nvim/assets/119894088/492d527b-a63f-4982-bcda-13515f4ab2d1)

**Comment by jake-stewart** [comment]
> There is no wrap_item_list in the config. Did you push it to branch 2.0?
> 
> ![image](https://user-images.githubusercontent.com/119894088/249951031-492d527b-a63f-4982-bcda-13515f4ab2d1.png)

it belongs in your jfind config. this is located in `~/.config/jfind/config.json`. make sure you have compiled latest jfind. see `jind --help` for more info
