### ISSUE TITLE
usage question: how to fill quickfix list or local buffer with results

### ISSUE THREAD

**Issue by matu3ba** [jake-stewart/jfind.nvim#18]
I know that this can also be done with setting up ripgrep via `vim.o.grepprg` and `vim.o.grepformat`, but this would additional effort to type.

1. Could this be a builtin like how telescope does it xor could the README document how the user can configure this/access the underlying neovim buffer and reformat it correctly (with the grepformat or errorfmt string)?
2. Could jfind mention how to do it correctly without jfind.nvim?

**Comment by matu3ba** [comment]
getqflist to get the qflist by parsing the buffer and subsequent setqflist https://vimhelp.org/builtin.txt.html#setqflist%28%29 should just work. Would be of course nice to do it in lua, but I dont think its worth the complexity.

**Comment by jake-stewart** [comment]
i'm not sure what you're asking for.

do you want the ability to run a jfind search, type some keys, and then dump all results to stdout instead of just one?

an example usage would be to livegrep using jfind, type a regular expression, and then dump the matches into your buffer or into quickfix list.

if this is what you're after, jfind cannot currently do this. it will be very simple to add, though.

@matu3ba

**Comment by matu3ba** [comment]
yes. both use cases.
For myself I'd like to implement also something along `rg --vimgrep 'searchpattern' | neovim gimmetheqflist`, for example via a shell alias/expansion.

Only providing the instructions with some lua functions should be enough, if the output can be piped.

**Comment by jake-stewart** [comment]
i think i’ll add a —select-all flag to jfind. when used, there will be no cursor line on the jfind window and pressing enter will dump all results to stdout. i will also add this to jfind.nvim which will return a list instead of a single result. if you can get the quickfix list to work with 1 result, then it should work the same once the list is added.

does this sound ok? @matu3ba 

i should be able to do it tonight.

**Comment by matu3ba** [comment]
> does this sound ok?

Yes, this sounds good.

**Comment by jake-stewart** [comment]
@matu3ba 

i added a `--select-all` flag to jfind. install latest jfind binary and update jfind.nvim (i pushed to 2.0 branch).

here is an example jfind.nvim lua call which uses `selectAll`.

```lua
local jfind = require("jfind")
local Key = require("jfind.key")

jfind.jfind({
    command = "seq",
    selectAll = true,
    callback = {
        [Key.DEFAULT] = function(results)
            print(vim.inspect(results))
        end
    }
})
```

or, you can run this in the terminal for the same effect: `jfind --command=seq --select-all`

i'll close this as completed. if there are any problems/questions or it doesn't work as expected i'll open it back up.

EDIT: forgot that this was all about the quickfix list. i'll work on that now.

**Comment by jake-stewart** [comment]
you can now provide `selectAll` to `findFile` and `liveGrep`. this will allow you to write a custom callback which fills the quickfixlist. here is an example for `liveGrep`:

```lua
local jfind = require("jfind")
local Key = require("jfind.key")

jfind.liveGrep({
    selectAll = true,
    callback = {
        [Key.DEFAULT] = function(results)
            local qflist = {};
            for i, v in pairs(results) do
                qflist[i] = {filename = v[1], lnum = v[2]}
            end
            vim.fn.setqflist(qflist)
        end
    }
})
```

note that the `results` for `liveGrep` returns an list instead of a single result since `selectAll` is used. `liveGrep` also returns its results as a list of `[string, int][]` (filename and line number) while regular `jfind()` and `findFile` return a list of strings.

EDIT: you can use `:copen` after running the above snippet to view your quickfix list. you probably know this already.

**Comment by jake-stewart** [comment]
this is a fairly poor solution to the problem.

you cannot for example run jfind with regular `liveGrep` and then suddenly decide to select all results into the quickfix list. you would have to cancel the search and reopen jfind in `select-all` mode.

ideally, jfind will be able to have a binding which applies `select-all` on the fly.

i plan for the next major feature of jfind to be lua scripting. this will make it very easy to create complex logic like this without introducing a bunch of arbitrary flags.

**Comment by matu3ba** [comment]
Thanks a lot. I find it already useful.
